# For more info on HTTP files go to https://aka.ms/vs/httpfile

@host = http://localhost:5000
@auth_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2OTE2NDAyMzUsImV4cCI6MTY5MjI0NTAzNSwiaWF0IjoxNjkxNjQwMjM1fQ.cRwz6PyEiByGCFyIKNT0Rk3uHH-6_4GL_QmefqyN_vM
@card_id = 9ff3a853-dea5-41aa-b4d8-1aaaa927d2b4

# Por favor, faça uma requisição para o endpoint /token para obter um token de autenticação.
# Depois, copie o token e cole no campo @auth_token acima.

POST {{host}}/token
Content-Type: application/json

{
    "login": "letscode",
    "senha": "lets@123"
}

###

GET {{host}}/Test
Authorization {{auth_token}}

###

GET {{host}}/cards
Authorization {{auth_token}}

###

GET {{host}}/cards/{{card_id}}
Authorization {{auth_token}}

###

POST {{host}}/cards/
Authorization {{auth_token}}
Content-Type application/json

{
    "titulo": "Fazer Compras",
    "conteudo": "Ir ao Superpao depois da aula comprar pao, presunto, queijo",
    "lista": "Compras"
}

###

PUT {{host}}/cards/{{card_id}}
Authorization {{auth_token}}
Content-Type application/json

{
    "id": "{{card_id}}",
    "titulo": "Fazer Tarefa de Casa",
    "conteudo": "Fazer tarefa de matematica",
    "lista": "Escola"
}

###

DELETE {{host}}/cards/{{card_id}}
Authorization {{auth_token}}